#ifndef _TIPOS_H_
#define _TIPOS_H_

typedef enum
{
	BIEN = 0,
	CANTIDAD_ARGUMENTOS = 1,
	LONGITUD_PALABRA = 2,
	CANTIDAD_INTENTOS = 3,
	INGRESO_UNA_LETRA = 4,
	NUMERO_NEGATIVO = 5,
	GANO = 20,
	PERDIO = 21,
	YA_SE_INTRODUJO,
	PERTENECE_A_LA_PALABRA,
	NO_PERTENECE_A_LA_PALABRA
}estado_t;

typedef unsigned int uint;

#endif
